Repository Kernel360/KDEV3_FlowSync_FE, pull requests merged in 2025-01, with the labels that each got.

#12 feat: 공통 레이아웃(Header, Sidebar) 및 SidebarTab 컴포넌트 구현
  app/layout.tsx
  app/page.tsx
  components/common/Pagination.tsx
  components/common/Profile.tsx
  components/common/SidebarTab.tsx
  components/layouts/Drawer.tsx
  components/layouts/Header.tsx
  components/layouts/Sidebar.tsx
  components/pages/FindPasswordPage/index.tsx
  components/pages/LoginPage/index.tsx
  components/pages/LogoutPage/index.tsx
  components/pages/ProjectApprovalPage/index.tsx
  components/pages/ProjectApprovalsPage/index.tsx
  components/pages/ProjectPage/index.tsx
  components/pages/ProjectTaskPage/index.tsx
  components/pages/ProjectTasksPage/index.tsx
  components/pages/ProjectsPage/index.tsx
  components/ui/segmented-control.tsx
  data/projects_mock_data.json
  data/users_mock_data.json
  next.config.ts
  types/profile.ts
Labels: FEATURE

#15 9 feature 글 생성 수정 폼 레이아웃 구현
  app/projects/[projectId]/process/page.tsx
  app/projects/[projectId]/tasks/[taskId]/edit/page.tsx
  app/projects/[projectId]/tasks/[taskId]/page.tsx
  app/projects/[projectId]/tasks/new/page.tsx
  package-lock.json
  package.json
  src/api/projects.ts
  src/components/common/CommentBox.tsx
  src/components/common/TaskComments.tsx
  src/components/common/TaskContents.tsx
  src/components/common/TaskForm.tsx
  src/components/common/backButton.tsx
  src/components/pages/ProjectTaskPage/index.tsx
  src/data/new_task_data.ts
  src/data/task_comments_data.ts
  src/data/task_data.ts
  src/data/목데이터이미지1.jpeg
  src/data/목데이터이미지2.jpeg
Labels: FEATURE

#17 13 feature 프로젝트 종합 대시보드 기능구현
  app/layout.tsx
  src/api/projects.ts
  src/components/common/BasicTable.tsx
  src/components/common/CustomBox.tsx
  src/components/common/Loading.tsx
  src/components/common/MSWComponent.tsx
  src/components/common/Pagination.tsx
  src/components/common/ProjectsStatusCard.tsx
  src/components/common/ProjectsStatusCards.tsx
  src/components/common/SearchSection.tsx
  src/components/common/SelectBox.tsx
  src/components/common/SidebarTab.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/components/ui/native-select.tsx
  src/data/projects_mock_data.json
  src/data/projects_page_1.json
  src/data/projects_page_2.json
  src/data/projects_page_3.json
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/types/project.ts
  src/utils/getTranslatedStatus.ts
  src/utils/temp.ts
Labels: FEATURE

#22 13 feature 프로젝트 종합 대시보드 기능구현
  app/globals.css
  app/layout.tsx
  app/page.module.css
  package-lock.json
  package.json
  src/api/projects.ts
  src/components/common/BasicTable.tsx
  src/components/common/CustomBox.tsx
  src/components/common/Pagination.tsx
  src/components/common/Profile.tsx
  src/components/common/ProjectsStatusCard.tsx
  src/components/common/ProjectsStatusCards.tsx
  src/components/common/SearchSection.tsx
  src/components/common/SelectBox.tsx
  src/components/common/SidebarTab.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Sidebar.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/components/ui/segmented-control.tsx
  src/components/ui/select.tsx
  src/context/ProjectsFilterContext.tsx
  src/context/SidebarContext.tsx
  src/mocks/handlers.ts
  src/types/search.ts
Labels: REFACTOR

#23 13 feature 프로젝트 종합 대시보드 기능구현
  src/components/common/Pagination.tsx
  src/components/pages/ProjectsPage/index.tsx
Labels: FEATURE

#27 13 feature 프로젝트 종합 대시보드 기능구현
  src/components/common/BasicTable.tsx
  src/components/common/CustomTable.tsx
  src/components/common/ProjectsList.tsx
  src/components/common/ProjectsStatusCards.tsx
  src/components/common/SearchSection.tsx
  src/components/common/SelectBox.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/types/project.ts
  src/types/search.ts
Labels: CHORE

#32 [FEATURE] 관리자 페이지 공통 레이아웃 구현
  app/admin/favicon.ico
  app/admin/layout.tsx
  app/admin/members/page.tsx
  app/admin/organizations/page.tsx
  app/admin/page.tsx
  package-lock.json
  src/components/common/Profile.tsx
  src/components/common/SidebarTab.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Sidebar.tsx
  src/components/pages/AdminDashboardPage/index.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrgsPage/index.tsx
  src/data/members_mock_data.json
  src/data/organizations_mock_data.json
  src/types/organization.ts
  src/types/profile.ts
Labels: FEATURE

#37 [FEATURE] 로그인 API 연동
  app/layout.tsx
  app/login/layout.tsx
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/axiosInstance.ts
  src/api/projects.ts
  src/components/pages/LoginPage/index.tsx
  src/context/RedirectContext.tsx
  src/hook/useRedirectIfLoggedIn.ts
  src/utils/isAdminCheck.tsx
Labels: FEATURE

#39 [FEATURE] 관리자 회원 관리 페이지 화면 UI 구현
  app/(home)/projects/[projectId]/tasks/[taskId]/edit/page.tsx
  src/types/taskTypes.ts
Labels: ERROR, FEATURE

#40 13 refactor, chore 프로젝트 종합 대시보드 기능구현
  src/api/projects.ts
  src/components/common/BoardSearchSection.tsx
  src/components/common/CommonTable.tsx
  src/components/common/ProgressStepButton.tsx
  src/components/common/ProgressStepSection.tsx
  src/components/common/ProjectInfo.tsx
  src/components/common/ProjectsSearchSection.tsx
  src/components/common/ProjectsStatusCards.tsx
  src/components/common/SelectBox.tsx
  src/components/pages/ProjectPage/index.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/context/ProjectsContext.tsx
  src/data/mock_tasks.json
  src/hook/useFetchData.tsx
  src/hook/useProgressData.tsx
  src/hook/useProjectData.tsx
  src/hook/useProjectInfo.tsx
  src/hook/useProjectList.tsx
  src/mocks/handlers.ts
  src/types/index.ts
  src/types/project.ts
Labels: REFACTOR, CHORE

#42 35 프로젝트별 대시보드 기능 구현
  app/layout.tsx
  src/api/projects.ts
  src/components/common/BoardCategorySelectBox.tsx
  src/components/common/BoardSearchSection.tsx
  src/components/common/BoardStatusSelectBox.tsx
  src/components/common/CommonTable.tsx
  src/components/common/Pagination.tsx
  src/components/common/ProgressStepButton.tsx
  src/components/common/ProgressStepSection.tsx
  src/components/common/ProjectStatusSelectBox.tsx
  src/components/common/ProjectsSearchSection.tsx
  src/components/common/ProjectsStatusCards.tsx
  src/components/common/SidebarTab.tsx
  src/components/common/TaskContent.tsx
  src/components/common/backButton.tsx
  src/components/layouts/Header.tsx
  src/components/pages/AdminDashboardPage/index.tsx
  src/components/pages/LoginPage/index.tsx
  src/components/pages/ProjectPage/index.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/hook/useProjectBoard.tsx
  src/hook/useProjectInfo.tsx
  src/hook/useProjectList.tsx
  src/types/api.ts
  src/types/index.ts
  src/types/pagination.ts
  src/types/project.ts
Labels: ERROR, FEATURE

#47 [FEATURE] 관리자 회원관리 페이지 - 회원 조회 API 연동
  src/api/members.ts
  src/components/common/MemberTable.tsx
  src/components/layouts/Header.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/hook/useMemberList.tsx
  src/types/api.ts
  src/types/member.ts
Labels: FEATURE

#49 pr템플릿용 컨벤션 정리 및 공유
  .github/PULL_REQUEST_TEMPLATE.md
  app/(home)/projects/[projectId]/tasks/[taskId]/page.tsx
  src/components/common/TaskContent.tsx
  src/components/pages/ProjectPage/index.tsx
  src/hook/useProjectBoard.tsx
Labels: CHORE

#55 [REFACTOR] 관리자-회원 공통 레이아웃 파일 생성
  app/(loggedIn)/(member)/layout.tsx
  app/(loggedIn)/layout.tsx
Labels: REFACTOR

#68 [FEATURE] 업체 생성 페이지 화면 UI 구현
  src/components/common/InputForm.module.css
  src/components/common/InputForm.tsx
  src/components/layouts/InputFormLayout.module.css
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/adminOrganizationsCreatePage/index.tsx
  src/components/pages/loginPage/index.tsx
  src/constants/defaultValues.ts
  src/constants/validationRules.ts
  src/hook/useForm.tsx
  src/types/index.ts
  src/types/inputForm.ts
Labels: FEATURE, REFACTOR

#70 [FEATURE] 회원 생성 페이지 화면 UI 구현
  src/api/auth.ts
  src/components/common/InputForm.tsx
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/adminMembersCreatePage/index.tsx
  src/components/pages/adminOrganizationsCreatePage/index.tsx
  src/components/pages/loginPage/index.tsx
  src/constants/defaultValues.ts
  src/constants/validationRules.ts
  src/hook/useForm.tsx
Labels: FEATURE

#80 [FEATURE] 업체 생성 API 연동
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/axiosInstance.ts
  src/api/organizations.ts
  src/app/(loggedIn)/projects/new/page.tsx
  src/components/pages/ProjectRegisterPage/components/ProjectForm.tsx
  src/components/pages/ProjectRegisterPage/components/SelectOrganizationSection.tsx
  src/components/pages/adminMembersCreatePage/index.tsx
  src/components/pages/adminOrganizationsCreatePage/index.tsx
  src/constants/defaultValues.ts
  src/types/index.ts
Labels: FEATURE

#86 83 커스텀 훅 리팩토링
  src/api/members.ts
  src/api/notices.ts
  src/api/organizations.ts
  src/api/projects.ts
  src/app/(loggedIn)/projects/[projectId]/tasks/new/page.tsx
  src/components/common/CommonTable.tsx
  src/components/common/FilterSelectBox.tsx
  src/components/common/ProgressStepSection.tsx
  src/components/common/ProjectInfoSection.tsx
  src/components/common/SearchSection.tsx
  src/components/common/StatusTag.tsx
  src/components/common/backButton.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/ProjectLayout.tsx
  src/components/pages/ProjectRegisterPage/index.tsx
  src/components/pages/QuestionReadPage/index.tsx
  src/components/pages/QuestionRegisterPage/index.tsx
  src/components/pages/adminMembersPage/components/MembersSearchSection.tsx
  src/components/pages/adminMembersPage/index.tsx
  src/components/pages/adminOrganizationsPage/components/OrganizationsSearchSection.tsx
  src/components/pages/adminOrganizationsPage/index.tsx
  src/components/pages/noticesPage/index.tsx
  src/components/pages/projectQuestionsPage/index.tsx
  src/components/pages/projectTasksPage/index.tsx
  src/components/pages/projectsPage/index.tsx
  src/hook/useFetchBoardList.tsx
  src/hook/useFetchData.tsx
  src/hook/useMemberList.tsx
  src/hook/useNoticeList.tsx
  src/hook/useOrganizationList.tsx
  src/hook/useProjectInfo.tsx
  src/hook/useProjectList.tsx
  src/hook/useProjectQuestionList.tsx
  src/hook/useProjectQuestionProgressStep.tsx
  src/hook/useProjectTaskList.tsx
  src/types/index.ts
Labels: REFACTOR

#90 회원 등록 API 연동
  src/api/members.ts
  src/api/organizations.ts
  src/components/pages/adminMembersCreatePage/index.tsx
  src/components/pages/adminMembersPage/index.tsx
  src/components/pages/adminOrganizationsCreatePage/index.tsx
  src/components/pages/adminOrganizationsPage/index.tsx
  src/constants/defaultValues.ts
  src/constants/validationRules.ts
  src/types/index.ts
Labels: FEATURE

#92 회원 상세조회 및 회원 정보 수정 API 연동
  src/api/members.ts
  src/components/common/InputForm.module.css
  src/components/common/InputForm.tsx
  src/components/layouts/InputFormLayout.module.css
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/adminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/adminMemberPage/index.tsx
  src/components/pages/adminMembersPage/index.tsx
  src/constants/validationRules.ts
  src/types/index.ts
Labels: FEATURE

#95 회원 탈퇴(삭제) API 연동
  src/api/members.ts
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/adminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/adminMembersPage/index.tsx
  src/components/ui/close-button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
  src/types/index.ts
Labels: FEATURE

#97 업체 상세조회 API연동
  src/api/members.ts
  src/api/organizations.ts
  src/components/common/InputForm.module.css
  src/components/common/InputForm.tsx
  src/components/layouts/InputFormLayout.module.css
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/adminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/adminMemberPage/index.tsx
  src/components/pages/adminOrganizationPage/components/organizationDetailForm.tsx
  src/components/pages/adminOrganizationPage/index.tsx
  src/components/pages/adminOrganizationsPage/index.tsx
  src/types/index.ts
Labels: FEATURE

#99 업체 생성 시 파일 업로드 API 연동
  src/api/organizations.ts
  src/components/common/InputForm.module.css
  src/components/common/InputForm.tsx
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/adminOrganizationsCreatePage/index.tsx
  src/constants/defaultValues.ts
  src/constants/validationRules.ts
  src/types/index.ts
Labels: ERROR, FEATURE
