Repository Kernel360/KDEV3_FlowSync_FE, pull requests merged in 2025-02, with the labels that each got.

#120 헤더 레이아웃 변경 및 로그인 사용자 프로필 조회 API 연동
  package-lock.json
  src/api/auth.ts
  src/app/(loggedIn)/layout.tsx
  src/app/globals.css
  src/app/login/layout.tsx
  src/components/common/InputForm.module.css
  src/components/layouts/Header.tsx
  src/components/layouts/Profile.tsx
  src/components/pages/loginPage/Login.module.css
  src/components/pages/loginPage/index.tsx
  src/components/ui/popover.tsx
  src/utils/getRandomProfileImage.ts
Labels: FEATURE

#122 로그아웃 API 연동
  src/components/layouts/Profile.tsx
Labels: FEATURE

#134 스타일 통일 및 반응형 디자인 작업
  src/app/(loggedIn)/layout.tsx
  src/components/common/CommonTable.tsx
  src/components/common/GuideButton.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Profile.tsx
  src/components/layouts/Sidebar.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/adminMembersPage/index.tsx
  src/components/pages/noticeRegisterPage/index.tsx
  src/components/pages/projectTasksPage/index.tsx
  src/components/pages/projectsPage/components/ProjectsStatusCard.tsx
  src/components/pages/projectsPage/components/ProjectsStatusCards.tsx
  src/components/pages/workFlowPage/index.tsx
  src/middleware.ts
Labels: CHORE

#143 업체 수정 시 입력 값 관련 에러 수정
  src/components/pages/adminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/adminMemberPage/index.tsx
  src/components/pages/adminOrganizationPage/components/organizationDetailForm.tsx
  src/components/pages/adminOrganizationPage/index.tsx
  src/constants/validationRules.ts
  src/middleware.ts
  src/types/index.ts
Labels: ERROR

#163 로고 이미지 출력 오류 해결
  src/app/(dashboard)/admin/members/[memberId]/page.tsx
  src/app/(dashboard)/admin/members/create/page.tsx
  src/app/(dashboard)/admin/members/page.tsx
  src/app/(dashboard)/admin/organizations/[organizationId]/page.tsx
  src/app/(dashboard)/admin/organizations/create/page.tsx
  src/app/(dashboard)/admin/organizations/page.tsx
  src/app/(dashboard)/notices/[noticeId]/page.tsx
  src/app/(dashboard)/notices/new/page.tsx
  src/app/(dashboard)/notices/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/[approvalId]/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/new/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/page.tsx
  src/app/(dashboard)/projects/[projectId]/edit/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/[questionId]/edit/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/[questionId]/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/new/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/page.tsx
  src/app/(dashboard)/projects/[projectId]/workflow/page.tsx
  src/app/(dashboard)/projects/new/page.tsx
  src/app/login/page.tsx
  src/components/common/ArticleForm.tsx
  src/components/pages/ApprovalReadPage/index.tsx
  src/components/pages/ProjectRegisterPage/components/ProjectForm.tsx
  src/components/pages/ProjectRegisterPage/index.tsx
Labels: ERROR

#164 레이아웃 버그 수정 및 기타 작업
  public/logo.png
  src/app/(dashboard)/admin/members/[memberId]/edit/page.tsx
  src/app/(dashboard)/admin/organizations/[organizationId]/edit/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/notices/[noticeId]/page.tsx
  src/app/(dashboard)/notices/new/page.tsx
  src/app/(dashboard)/notices/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/[approvalId]/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/new/page.tsx
  src/app/(dashboard)/projects/[projectId]/edit/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/[questionId]/edit/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/[questionId]/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/new/page.tsx
  src/app/(dashboard)/projects/[projectId]/workflow/page.tsx
  src/app/(dashboard)/projects/create/page.tsx
  src/app/(dashboard)/projects/new/page.tsx
  src/app/ActionButtons.module.css
  src/components/common/ArticleForm.tsx
  src/components/common/ButtonEditDelete.tsx
  src/components/common/ButtonRegister.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/InputFormLayout copy.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/AdminMemberEditPage/index.tsx
  src/components/pages/AdminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/AdminMemberPage/index.tsx
  src/components/pages/AdminMembersCreatePage/components/SelectOrganization.tsx
  src/components/pages/AdminMembersCreatePage/index.tsx
  src/components/pages/AdminOrganizationEditPage/index.tsx
  src/components/pages/AdminOrganizationPage/index.tsx
  src/components/pages/ApprovalReadPage/index.tsx
  src/components/pages/LoginPage/Login.module.css
  src/components/pages/LoginPage/index.tsx
  src/components/pages/NoticePage/index.tsx
  src/components/pages/NoticesNewPage/edit.css
  src/components/pages/NoticesNewPage/index.tsx
  src/components/pages/ProjectApprovalPage/components/SignToApprove.tsx
  src/components/pages/ProjectApprovalPage/index.tsx
  src/components/pages/ProjectApprovalsNewPage/components/SignUpload.tsx
  src/components/pages/ProjectApprovalsNewPage/edit.css
  src/components/pages/ProjectApprovalsNewPage/index.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectQuestionEditPage/components/QuestionEditForm.tsx
  src/components/pages/ProjectQuestionEditPage/index.tsx
  src/components/pages/ProjectQuestionPage/index.tsx
  src/components/pages/ProjectQuestionsNewPage/edit.css
  src/components/pages/ProjectQuestionsNewPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/index.tsx
  src/components/pages/ProjectsCreatePage/components/ContentSection.tsx
  src/components/pages/ProjectsCreatePage/components/DateSection.tsx
  src/components/pages/ProjectsCreatePage/components/HeaderSection.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/components/pages/ProjectsCreatePage/components/SelectOrganizationSection.tsx
  src/components/pages/ProjectsCreatePage/components/dateSection.css
  src/components/pages/ProjectsCreatePage/index.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/middleware.ts
Labels: ERROR, CHORE

#166 merge 충돌 오류 해결
  public/flowSync_Logo.png
  src/app/(dashboard)/admin/members/[memberId]/page.tsx
  src/app/(dashboard)/admin/members/create/page.tsx
  src/app/(dashboard)/admin/members/page.tsx
  src/app/(dashboard)/admin/organizations/[organizationId]/page.tsx
  src/app/(dashboard)/admin/organizations/create/page.tsx
  src/app/(dashboard)/admin/organizations/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/[approvalId]/edit/page.tsx
  src/app/(dashboard)/projects/[projectId]/approvals/page.tsx
  src/app/(dashboard)/projects/[projectId]/questions/page.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/components/common/ActionButtons.module.css
  src/components/pages/LoginPage/Login.module.css
  src/components/pages/LoginPage/index.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/middleware.ts
Labels: ERROR

#170 공지사항 및 기타 작업
  src/api/notices.ts
  src/components/common/CommonTable.tsx
  src/components/common/FilterSelectBox.tsx
  src/components/common/NoticeArticleContent.tsx
  src/components/common/ProgressStepSection.tsx
  src/components/common/SearchSection.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/NoticePage/index.tsx
  src/components/pages/NoticesPage/index.tsx
  src/components/pages/ProjectApprovalPage/index.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/hook/useFetchBoardList.ts
  src/hook/useProjectInfiniteScroll.ts
  src/types/index.ts
Labels: ERROR, FEATURE

#176 진척관리게시판 관리단계 변경 기능 구현
  src/api/projects.ts
  src/app/(dashboard)/projects/[projectId]/layout.tsx
  src/app/(dashboard)/projects/layout.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/common/SearchSection.tsx
  src/components/layouts/ProjectLayout.tsx
  src/components/pages/ProjectQuestionsNewPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectManagementStepCards.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectsManagementStepCard.tsx
  src/components/pages/ProjectWorkFlowPage/index.tsx
  src/components/pages/ProjectsPage/components/ProjectsManagementStepCards.tsx
  src/context/ProjectInfoContext.tsx
  src/hook/useFetchData.ts
  src/middleware.ts
Labels: FEATURE

#177 프로젝트 상세 조회/수정/삭제 API 연동
  src/api/getMembersApi.ts
  src/api/getOrganization.ts
  src/api/members.ts
  src/api/projects.ts
  src/api/registerProject.ts
  src/app/globals.css
  src/components/common/BackButton.tsx
  src/components/common/ButtonEditDelete.tsx
  src/components/common/ConfirmDialogEditDelete.tsx
  src/components/common/EditButton.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/InputFormLayout copy.tsx
  src/components/layouts/InputFormLayout.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/ProjectEditPage/index.tsx
  src/components/pages/ProjectsCreatePage/components/ContentSection.tsx
  src/components/pages/ProjectsCreatePage/components/DateSection.tsx
  src/components/pages/ProjectsCreatePage/components/HeaderSection.tsx
  src/components/pages/ProjectsCreatePage/components/OrganizationSelector.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/components/pages/ProjectsCreatePage/components/SelectOrganizationSection.tsx
  src/components/pages/ProjectsCreatePage/components/dateSection.css
  src/components/pages/ProjectsCreatePage/index.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/hook/useProjectInfiniteScroll.ts
  src/middleware.ts
  src/types/index.ts
Labels: FEATURE

#183 회원 생성 시 업체 검색 기능 구현 및 회원 활성화/비활성화 API 연동
  src/api/members.ts
  src/api/projects.ts
  src/components/common/InputForm.module.css
  src/components/layouts/Profile.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/AdminMembersCreatePage/index.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationPage/components/organizationDetailForm.tsx
  src/components/ui/switch.tsx
  src/middleware.ts
  src/types/index.ts
Labels: FEATURE

#185 회원 목록 테이블 수정 및 삭제 버튼 구현
  src/app/globals.css
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
Labels: FEATURE

#188 전체 레이아웃 스타일링
  src/app/globals.css
  src/components/common/ArticleContent.tsx
  src/components/common/CommentBox.tsx
  src/components/common/CommonTable.tsx
  src/components/common/CreateButton.tsx
  src/components/common/ProgressStepButton.tsx
  src/components/common/ProgressStepSection.tsx
  src/components/common/ProjectInfoSection.tsx
  src/components/common/SearchSection.tsx
  src/components/common/StatusTag.tsx
  src/components/layouts/InputFormLayout.module.css
  src/components/layouts/InputFormLayout.tsx
  src/components/layouts/ProjectLayout.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/ProjectApprovalPage/index.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectManagementStepCards.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectsManagementStepCard.tsx
  src/components/pages/ProjectWorkFlowPage/index.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/utils/formatDateUtil.ts
Labels: CHORE

#190 업체 목록 수정, 삭제 버튼 추가
  src/api/organizations.ts
  src/components/layouts/SidebarTab.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
  src/hook/useFetchBoardList.ts
Labels: FEATURE

#197 [FEATURE] 업체 별 소속회원 및 참여 프로젝트 목록 조회 기능 구현
  src/api/members.ts
  src/api/projects.ts
  src/app/(dashboard)/admin/members/[memberId]/edit/page.tsx
  src/app/(dashboard)/admin/organizations/[organizationId]/edit/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/globals.css
  src/components/common/CommonTable.tsx
  src/components/common/ConfirmDialog.tsx
  src/components/common/SearchSection.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/InputFormLayout.module.css
  src/components/layouts/InputFormLayout.tsx
  src/components/pages/AdminMemberEditPage/index.tsx
  src/components/pages/AdminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationEditPage/index.tsx
  src/components/pages/AdminOrganizationPage/components/organizationDetailForm.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectManagementStepCards.tsx
  src/components/pages/ProjectsCreatePage/components/OrganizationSelector.tsx
  src/hook/useFetchBoardList.ts
  src/types/index.ts
Labels: FEATURE

#199 프로젝트 상세페이지 레이아웃 수정
  src/app/(dashboard)/layout.tsx
  src/components/common/FilterSelectBox.tsx
  src/components/common/ProgressStepButton.tsx
  src/components/common/ProgressStepSection.tsx
  src/components/common/ProjectInfoSection222.tsx
  src/components/common/SearchSection.tsx
  src/components/layouts/ProjectLayout.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectQuestionsPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/components/DateSection.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectManagementStepCards.tsx
  src/components/pages/ProjectWorkFlowPage/index.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/types/index.ts
Labels: FEATURE

#203 전체 레이아웃 리팩토링 및 안정화
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/styles.module.css
  src/components/common/FilterSelectBox.tsx
  src/components/common/SearchSection.tsx
  src/components/layouts/CommonFormDetailLayout.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/InputFormLayout.tsx
  src/components/layouts/Profile.tsx
  src/components/layouts/Sidebar.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/AdminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/AdminMembersCreatePage/index.tsx
  src/components/pages/AdminOrganizationPage/components/organizationDetailForm.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/index.tsx
  src/components/pages/ProjectsPage/components/ProjectsManagementStepCards.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/styles/layoutStyles.ts
Labels: FEATURE, REFACTOR

#207 진행단계 커스텀 UI 구현
  package-lock.json
  package.json
  src/api/notices.ts
  src/api/projects.ts
  src/components/common/ConfirmDialog.tsx
  src/components/pages/ProjectWorkFlowPage/components/DraggableProgressStep.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectManagementStepCards.tsx
  src/components/pages/ProjectWorkFlowPage/index.tsx
  src/hook/useMutationData.ts
  src/types/index.ts
Labels: FEATURE

#213 입력 폼 레이아웃 통합 리팩토링 및 전반적인 UI/UX 개선
  src/app/(dashboard)/layout.tsx
  src/app/globals.css
  src/app/login/layout.tsx
  src/components/common/CommentItem.tsx
  src/components/common/CreateButton.tsx
  src/components/common/FilterSelectBox.tsx
  src/components/common/InputForm.module.css
  src/components/common/InputForm.tsx
  src/components/common/LinkAddSection.tsx
  src/components/common/Pagination.tsx
  src/components/common/ProjectInfoSection.tsx
  src/components/common/ProjectInfoSection222.tsx
  src/components/layouts/CommonFormDetailLayout.tsx
  src/components/layouts/InputFormLayout.module.css
  src/components/layouts/InputFormLayout.tsx
  src/components/layouts/ProjectLayout.tsx
  src/components/pages/AdminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/AdminMembersCreatePage/index.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationPage/components/organizationDetailForm.tsx
  src/components/pages/AdminOrganizationsCreatePage/index.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
  src/components/pages/LoginPage/Login.module.css
  src/components/pages/LoginPage/index.tsx
  src/components/pages/NoticeEditPage/index.tsx
  src/components/pages/NoticePage/index.tsx
  src/components/pages/NoticesNewPage/index.tsx
  src/components/pages/NoticesPage/index.tsx
  src/components/pages/ProjectApprovalEditPage/index.tsx
  src/components/pages/ProjectApprovalPage/index.tsx
  src/components/pages/ProjectApprovalsNewPage/index.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectEditPage/index.tsx
  src/components/pages/ProjectQuestionEditPage/index.tsx
  src/components/pages/ProjectQuestionPage/index.tsx
  src/components/pages/ProjectQuestionsNewPage/index.tsx
  src/components/pages/ProjectQuestionsPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/components/ProjectManagementStepCards.tsx
  src/components/pages/ProjectsCreatePage/components/ContentSection.tsx
  src/components/pages/ProjectsCreatePage/components/OrganizationSelector.tsx
  src/components/pages/ProjectsCreatePage/index.tsx
  src/components/pages/ProjectsPage/components/ProjectsManagementStepCards.tsx
  src/constants/defaultValues.ts
  src/styles/layoutStyles.ts
  src/types/index.ts
Labels: FEATURE, REFACTOR

#222 QA 테스트 결과 반영 및 UI/UX 개선, 통합
  package-lock.json
  package.json
  public/badge-x.png
  src/api/members.ts
  src/api/organizations.ts
  src/api/projects.ts
  src/components/common/ArticleContent.tsx
  src/components/common/CommentItem.tsx
  src/components/common/FilterSelectBox.tsx
  src/components/common/Pagination.tsx
  src/components/common/ProjectInfoSection.tsx
  src/components/common/SearchSection.tsx
  src/components/layouts/InputFormLayout.tsx
  src/components/layouts/ProjectLayout.tsx
  src/components/pages/AdminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/AdminMembersCreatePage/index.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationPage/components/OrganizationDetailPage.tsx
  src/components/pages/AdminOrganizationPage/index.tsx
  src/components/pages/AdminOrganizationsCreatePage/index.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
  src/components/pages/NoticePage/components/NoticeArticleContent.tsx
  src/components/pages/NoticesNewPage/index.tsx
  src/components/pages/NoticesPage/index.tsx
  src/components/pages/ProjectApprovalPage/index.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectQuestionPage/index.tsx
  src/components/pages/ProjectQuestionsPage/index.tsx
  src/components/pages/ProjectsCreatePage/components/OrganizationSelector.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/constants/validationRules.ts
  src/hook/useForm.ts
  src/hook/useInputFormatter.ts
  src/hook/useMutationData.ts
  src/hook/useOrganizationSearch.ts
  src/hook/useValidation.ts
  src/types/index.ts
  src/utils/formatDateUtil.ts
Labels: ERROR, REFACTOR

#225 사이드바 프로젝트 목록 UI/UX 개선
  src/components/layouts/Sidebar.tsx
  src/components/layouts/SidebarTab.tsx
  src/components/pages/ProjectsPage/index.tsx
Labels: CHORE

#229 날짜 관련 에러 해결 및 UI/UX 개선
  src/components/common/ArticleForm.tsx
  src/components/common/CommentBox.tsx
  src/components/common/CommentItem.tsx
  src/components/common/DropDownInfoBottom.tsx
  src/components/common/LinkAddSection.tsx
  src/components/layouts/Profile.tsx
  src/components/layouts/Sidebar.tsx
  src/components/pages/AdminMemberPage/components/MemberDetailForm.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationsPage/index.tsx
  src/components/pages/LoginPage/index.tsx
  src/components/pages/ProjectsCreatePage/components/DateSection.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/components/pages/ProjectsPage/components/ColorCustomizer.tsx
  src/components/pages/ProjectsPage/components/ProjectsManagementStepCards.tsx
  src/components/pages/ProjectsPage/index.tsx
  src/utils/formatDateUtil.ts
Labels: FEATURE, CHORE

#235 alert 구문 toast 메시지로 변경 및 UI/UX 개선
  src/api/ReadArticle.ts
  src/api/RegisterArticle.ts
  src/api/commentAPI.ts
  src/api/members.ts
  src/api/projects.ts
  src/api/signature.ts
  src/app/(dashboard)/layout.tsx
  src/components/common/CommentBox.tsx
  src/components/common/CommentItem.tsx
  src/components/common/InputForm.tsx
  src/components/pages/AdminMembersCreatePage/components/SelectOrganization.tsx
  src/components/pages/AdminMembersCreatePage/index.tsx
  src/components/pages/AdminMembersPage/index.tsx
  src/components/pages/AdminOrganizationPage/components/OrganizationDetailPage.tsx
  src/components/pages/LoginPage/index.tsx
  src/components/pages/NoticesPage/index.tsx
  src/components/pages/ProjectApprovalEditPage/components/ApprovalEditForm.tsx
  src/components/pages/ProjectApprovalEditPage/components/EditSignUpload.tsx
  src/components/pages/ProjectApprovalPage/components/SignToApprove.tsx
  src/components/pages/ProjectApprovalPage/index.tsx
  src/components/pages/ProjectApprovalsNewPage/index.tsx
  src/components/pages/ProjectApprovalsPage/index.tsx
  src/components/pages/ProjectQuestionEditPage/components/QuestionEditForm.tsx
  src/components/pages/ProjectQuestionsNewPage/index.tsx
  src/components/pages/ProjectQuestionsPage/index.tsx
  src/components/pages/ProjectWorkFlowPage/components/AddProgressStepModal.tsx
  src/components/pages/ProjectWorkFlowPage/components/EditProgressStepModal.tsx
  src/components/pages/ProjectsCreatePage/components/ContentSection.tsx
  src/components/pages/ProjectsCreatePage/components/OrganizationSelector.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/hook/useMutationData.ts
  src/utils/showToast.ts
Labels: FEATURE, CHORE

#238 유효성 검사 로직 구현 및 프로젝트 고객사/담당자 배정 오류 해결
  src/components/pages/ProjectsCreatePage/components/OrganizationSelector.tsx
  src/components/pages/ProjectsCreatePage/components/ProjectForm.tsx
  src/constants/validationRules.ts
  src/hook/useValidation.ts
Labels: ERROR, FEATURE

#245 README 업데이트
  README.md
Labels: DOCS

#246 README 업데이트
  README.md
Labels: DOCS
